### ISSUE TITLE
DatabaseChain not working on version 0.0.158 for SQLLite

### ISSUE THREAD

**Issue by vermion** [hwchase17/langchain#4175]
### System Info

Python 3.10
0.0.158
Tried to upgrade Langchain to latest version and the SQLChain no longer works
Looks like the latest version has changed the way SQL chains are initialized.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

For version 0.0.158 the way SQL chains are initialized has changed, but the dicumentation has not been updated
db_chain = SQLDatabaseChain.from_llm(llmChat, db) 

 The above code throws the following error:  (<class 'ImportError'>, ImportError("cannot import name 'CursorResult' from 'sqlalchemy' (C:\Projects\llmsql\lib\site-packages\sqlalchemy\init.py)"), <traceback object at 0x0000026D7EDC4680>)

### Expected behavior

Should just work as before.

**Comment by bmanturner** [comment]
SQLAlchemy no longer works on v1.x. CursorResult is in v2.

**Comment by vermion** [comment]
So for now it is just broken? Is there anything I can do to fix this it?

**Comment by bmanturner** [comment]
You can update SQLAlchemy. I was surprised they broke compatibility with v1 so quickly after supporting v2; maybe it wasn't intentional

**Comment by Buckler89** [comment]
Updating SQLALchemy to 2.0.12 works for me

**Comment by vermion** [comment]
Ok thanks
