### ISSUE TITLE
ERROR:root:'OpenAIEmbeddings' object has no attribute 'max_retries' - VERSION 0.0.106 and up

### ISSUE THREAD

**Issue by kre8mymedia** [hwchase17/langchain#1759]
**Summary:**
Occurring in [Chat Langchain Demo](https://github.com/hwchase17/chat-langchain) when upgrading from 0.0.105 -> 0.0.106 getting 
 `ERROR:root:'OpenAIEmbeddings' object has no attribute 'max_retries'`
 
 This occurs AFTER the user sends their first message, instantly receive back the error in the logs. The error is thrown from this try catch block.  https://github.com/hwchase17/chat-langchain/blob/ba456378e04125ccbdc7715f5be17114df2ee2e1/main.py#L68
 
 My suspicion is that it originates within the `get_chain` method, as the ChatResponse's are really just validation and don't touch Embeddings. Seems like may be deeper.

**Expected Behavior (v0.0.105):**
![image](https://user-images.githubusercontent.com/40816745/226126267-dc013237-636d-43a3-8b51-dd2cac6914b4.png)

**Actual Behavior (v0.0.106):**
![image](https://user-images.githubusercontent.com/40816745/226126159-fb224124-fb75-4bfa-89d9-7eb1086577b0.png)

**Frequency:**
Whenever creating a USER message in chat-langchain when upgrading past v0.0.105

**Environment:**
[List the operating system, browser, device, and any other relevant software or hardware information]
https://github.com/hwchase17/chat-langchain

**Comment by theanirudhvyas** [comment]
I think I've found the issue here.
For me, this happened when I had ingested the documents using an older version (<= v0.0.105) version of langchain and was trying to use v0.0.106 of langchain. 
Since we are dumping the object in a pickle file, the OpenAIEmbeddings object that is loaded from the file does not have a `max_retries` attribute. Verified that it does not have a `chunk_size` attribute as well.

This issue should be fixed by re ingesting your files with the newer version of Langchain.
But I'll raise a PR to fix this issue nonetheless. cc: @hwchase17

**Comment by kre8mymedia** [comment]
I recently began refactoring code to update to higher versions for this. I  believe it could be due to needing to install `tiktoken` this seemed to be the key to get me past it. Kept getting max_retries errors in console built a unit test and saw this.

![image](https://user-images.githubusercontent.com/40816745/231945601-fb9a812b-2e26-4394-bde5-26574acdcaa7.png)


That led me to remember needing it in colab.
