### ISSUE TITLE
ImportError: cannot import name 'CursorResult' from 'sqlalchemy'

### ISSUE THREAD

**Issue by bacharSalleh** [hwchase17/langchain#4142]
### System Info

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
aiohttp                   3.8.3           py310h5eee18b_0  
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_0    conda-forge
blas                      1.0                         mkl  
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2022.12.7       py310h06a4308_0  
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0  
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cryptography              3.4.8           py310h685ca39_1    conda-forge
dataclasses-json          0.5.7              pyhd8ed1ab_0    conda-forge
frozenlist                1.3.3           py310h5eee18b_0  
greenlet                  2.0.1           py310h6a678d5_0  
idna                      3.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
langchain                 0.0.158            pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
marshmallow               3.19.0             pyhd8ed1ab_0    conda-forge
marshmallow-enum          1.5.1              pyh9f0ad1d_3    conda-forge
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0           py310ha2c4b55_0    conda-forge
mkl_fft                   1.3.1           py310hd6ae3a3_0  
mkl_random                1.2.2           py310h00e6091_0  
multidict                 6.0.2           py310h5eee18b_0  
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
numexpr                   2.8.4           py310h8879344_0  
numpy                     1.24.3          py310hd5efca6_0  
numpy-base                1.24.3          py310h8e6c178_0  
openapi-schema-pydantic   1.2.4              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       22.2.2                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.2          py310h5eee18b_0  
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.9               h7a1cb2a_2  
python_abi                3.10                    2_cp310    conda-forge
pyyaml                    6.0             py310h5764c6d_4    conda-forge
readline                  8.2                  h5eee18b_0  
requests                  2.29.0             pyhd8ed1ab_0    conda-forge
setuptools                66.0.0          py310h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlalchemy                1.4.39          py310h5eee18b_0  
sqlite                    3.41.2               h5eee18b_0  
stringcase                1.2.0                      py_0    conda-forge
tenacity                  8.2.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
typing_inspect            0.8.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4          py310h06a4308_0  
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.7.2           py310h5764c6d_2    conda-forge
zlib                      1.2.13               h5eee18b_0  

Traceback (most recent call last):
  File "/home/bachar/projects/op-stack/./app.py", line 1, in <module>
    from langchain.document_loaders import DirectoryLoader
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 15, in <module>
    from langchain.agents.tools import InvalidTool
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/tools/__init__.py", line 32, in <module>
    from langchain.tools.vectorstore.tool import (
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/tools/vectorstore/tool.py", line 13, in <module>
    from langchain.chains import RetrievalQA, RetrievalQAWithSourcesChain
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/chains/__init__.py", line 19, in <module>
    from langchain.chains.loading import load_chain
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/chains/loading.py", line 24, in <module>
    from langchain.chains.sql_database.base import SQLDatabaseChain
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/chains/sql_database/base.py", line 15, in <module>
    from langchain.sql_database import SQLDatabase
  File "/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/langchain/sql_database.py", line 8, in <module>
    from sqlalchemy import (
ImportError: cannot import name 'CursorResult' from 'sqlalchemy' (/home/bachar/projects/op-stack/venv/lib/python3.10/site-packages/sqlalchemy/__init__.py)
(/home/bachar/projects/op-stack/venv) 

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [X] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

from langchain.document_loaders import DirectoryLoader

docs =  DirectoryLoader("./pdfs", "**/*.pdf").load()

### Expected behavior

no errors should be thrown

**Comment by wally2511** [comment]
I'm having the exact same problem after upgrading to 0.0.158.

It appears when trying to import the libraries

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[9], line 11
      9 from langchain.vectorstores import Chroma
     10 #from langchain import OpenAI
---> 11 from langchain.chains import  ConversationalRetrievalChain
     12 #from langchain.chains.question_answering import load_qa_chain
     13 from langchain.llms import OpenAI

File [c:\Users\matthewwalter\Anaconda3\envs\yhi_langchain\lib\site-packages\langchain\__init__.py:6](file:///C:/Users/matthewwalter/Anaconda3/envs/yhi_langchain/lib/site-packages/langchain/__init__.py:6)
      3 from importlib import metadata
      4 from typing import Optional
----> 6 from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
      7 from langchain.cache import BaseCache
      8 from langchain.chains import (
      9     ConversationChain,
     10     LLMBashChain,
   (...)
     18     VectorDBQAWithSourcesChain,
     19 )

File [c:\Users\matthewwalter\Anaconda3\envs\yhi_langchain\lib\site-packages\langchain\agents\__init__.py:10](file:///C:/Users/matthewwalter/Anaconda3/envs/yhi_langchain/lib/site-packages/langchain/agents/__init__.py:10)
      1 """Interface for agents."""
      2 from langchain.agents.agent import (
      3     Agent,
...
     16 )
     17 from sqlalchemy.engine import Engine
     18 from sqlalchemy.exc import ProgrammingError, SQLAlchemyError

ImportError: cannot import name 'CursorResult' from 'sqlalchemy' ([c:\Users\matthewwalter\Anaconda3\envs\yhi_langchain\lib\site-packages\sqlalchemy\__init__.py](file:///C:/Users/matthewwalter/Anaconda3/envs/yhi_langchain/lib/site-packages/sqlalchemy/__init__.py))`

**Comment by SamCox822** [comment]
Upgrading SQLAlchemy solves this problem for me!

**Comment by rvipandey** [comment]
pip install SQLAlchemy==2.0.1 worked for me !

**Comment by jpigla** [comment]
Unfortunately version 2.0.1 or above (-U) does not work, the nearly same error.

ImportError                               Traceback (most recent call last)
Cell In[2], line 6
      4 from langchain.vectorstores import Chroma
      5 from langchain.text_splitter import CharacterTextSplitter
----> 6 **from langchain import OpenAI, VectorDBQA**
      7 from langchain.document_loaders import DirectoryLoader

**Comment by rvipandey** [comment]
Can you share the screenshot, exact error ?

**Comment by jpigla** [comment]
I just stole the commit from above https://github.com/hwchase17/langchain/commit/fea639c1fc1ac324f1300016a02b6d30a2f8d249 and it works with langchain-0.0.158 

👍

**Comment by rvipandey** [comment]
for me
langchain                 0.0.158 
sqlalchemy               2.0.1

**Comment by ms-robot-please** [comment]
I got it to work with a simple: pip install SQLAlchemy==2.0.1

**Comment by xsqian** [comment]
I am still get this:
`ImportError: cannot import name 'Row' from 'sqlalchemy' (/User/.conda/envs/llm/lib/python3.9/site-packages/sqlalchemy/__init__.py)`
lanchain 0.0.321
SQLAlchemy 2.0.1

**Comment by s-demp** [comment]
> I am still get this: `ImportError: cannot import name 'Row' from 'sqlalchemy' (/User/.conda/envs/llm/lib/python3.9/site-packages/sqlalchemy/__init__.py)` lanchain 0.0.321 SQLAlchemy 2.0.1

removing the row import from sqlalchemy on line 45 of the vectorestores/cache.py file fixes this, if you are looking for a temp solution
