### ISSUE TITLE
Error with `create_sql_agent` after updating to v0.0.137

### ISSUE THREAD

**Issue by timothepearce** [hwchase17/langchain#2722]
After updating to v.0.0.137 version, I now have an error while executing the following script (from the documentation):

```python
import os
from langchain.agents import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit
from langchain.sql_database import SQLDatabase
from langchain.llms.openai import OpenAI

os.environ["OPENAI_API_KEY"] = "sk-xxxxxxxxxxxxxx"
db = SQLDatabase.from_uri("mysql://user:password@localhost:db_port/db_name")
llm = OpenAI(temperature=0)
toolkit = SQLDatabaseToolkit(db=db)

agent_executor = create_sql_agent(
    llm=llm,
    toolkit=toolkit,
    verbose=True
)

agent_executor.run("A human to SQL request")
```

The error: "AttributeError: type object 'QueryCheckerTool' has no attribute 'llm'"

<img width="842" alt="Capture d’écran 2023-04-11 à 19 04 18" src="https://user-images.githubusercontent.com/11693661/231237020-3ac589d1-89ca-4044-bd24-8b0512734fcf.png">

[This PR](https://github.com/hwchase17/langchain/pull/2655) breaks something, but I can't find how to debug the error.

Can someone help me debug it?

Thanks ❤️

**Comment by DavidBurela** [comment]
I have the same issue. 
`create_sql_agent()` works in 0.0.136, but 0.0.137 seems to have a regression that breaks.

**Comment by timothepearce** [comment]
Thanks, @ndaugreal, but I had the same issue as before with the code you provided.

I opened a PR with a different approach and added a `@root_validator` to the `llm_chain.` It seems to be a lot of validation, but at least it works. If you find a better way, let me know!

**Comment by ndaugreal** [comment]
Hi @timothepearce Interesting because I tested my code before posting it and it did work at least from my end. However I think I like your solution - which is more Pydantic-native! :-)
